// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWV6_lBLiizwBl5uQ6_WS3Hk6IGsJH40',
    appId: '1:345800869409:web:fa3b7e206481cb971f0560',
    messagingSenderId: '345800869409',
    projectId: 'plantify-a8e3b',
    authDomain: 'plantify-a8e3b.firebaseapp.com',
    storageBucket: 'plantify-a8e3b.appspot.com',
    measurementId: 'G-T90ZQJFHDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Qy6rUgdBfsTG6QtFzF6rSbYYWPuvUUU',
    appId: '1:345800869409:android:9e7f5d5535531ad01f0560',
    messagingSenderId: '345800869409',
    projectId: 'plantify-a8e3b',
    storageBucket: 'plantify-a8e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGmtRjAviYLBB3bfuGXSULQ0CIWY5zBo',
    appId: '1:345800869409:ios:0cff9289693f09eb1f0560',
    messagingSenderId: '345800869409',
    projectId: 'plantify-a8e3b',
    storageBucket: 'plantify-a8e3b.appspot.com',
    iosBundleId: 'com.example.plantify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcWV6_lBLiizwBl5uQ6_WS3Hk6IGsJH40',
    appId: '1:345800869409:web:58b6b879e39aae101f0560',
    messagingSenderId: '345800869409',
    projectId: 'plantify-a8e3b',
    authDomain: 'plantify-a8e3b.firebaseapp.com',
    storageBucket: 'plantify-a8e3b.appspot.com',
    measurementId: 'G-2580Z53KYB',
  );
}
